$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$SpawnFile = Join-Path $Root 'npc\re\mobs\tra_fild_123.txt'
$OutFile = Join-Path $Root 'db\import\mob_avail.yml'

$names = [ordered]@{}
Get-Content $SpawnFile | ForEach-Object {
	if ($_ -match 'monster\s+.+\s+\d+,.*//\s*(\S+)') { $names[$matches[1]] = $true }
}

function Get-SpriteMap([string]$Aegis) {
	if ($Aegis -eq 'S_DUMMY_100_HUMANP') {
		return @{ Sprite = 'JOB_SWORDMAN'; Extra = @('Sex: Male') }
	}
	if ($Aegis -eq 'S_DUMMY_100_DORAMP') {
		return @{ Sprite = 'JOB_SUMMONER'; Extra = @('Sex: Female') }
	}
	$Upper = $Aegis.ToUpper()
	if ($Upper -match 'XLARGE') { return @{ Sprite = 'DUMMY_150'; Extra = @() } }
	if ($Upper -match 'LARGE') { return @{ Sprite = 'DUMMY_100'; Extra = @() } }
	if ($Upper -match 'MEDIUM') { return @{ Sprite = 'DUMMY_50'; Extra = @() } }
	if ($Upper -match 'SMALL') { return @{ Sprite = 'DUMMY_10'; Extra = @() } }
	return @{ Sprite = 'DUMMY_100'; Extra = @() }
}

$Lines = @(
	'# Training ground dummy sprite remaps (tra_fild01/02/03)',
	'# Generated by tools/gen_mob_avail.ps1',
	'# Remaps S_DUMMY_* mobs to legacy DUMMY_10/50/100/150 sprites.',
	'',
	'Header:',
	'  Type: MOB_AVAIL_DB',
	'  Version: 1',
	'',
	'Body:'
)

foreach ($Name in ($names.Keys | Sort-Object)) {
	$Map = Get-SpriteMap $Name
	$Lines += "  - Mob: $Name"
	$Lines += "    Sprite: $($Map.Sprite)"
	foreach ($Extra in $Map.Extra) { $Lines += "    $Extra" }
}

$OutDir = Split-Path -Parent $OutFile
if (-not (Test-Path $OutDir)) { New-Item -ItemType Directory -Path $OutDir | Out-Null }
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
$text = ($Lines -join "`n").TrimEnd() + "`n"
[IO.File]::WriteAllText($OutFile, $text, $utf8NoBom)
Write-Host "Wrote $($names.Count) entries to $OutFile"
