#!/usr/bin/env python3
"""List or generate mob_avail.yml for training dummy mobs in tra_fild.

Native S_DUMMY_* sprites work only when the client mob database resolves those
IDs to s_dummy_* resources. If the client shows "Cannot find File: sprite\\...\\.spr"
or crashes in the training ground, generate db/import/mob_avail.yml:

    python tools/gen_training_dummy_avail.py --write
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPAWN_FILE = ROOT / "npc" / "re" / "mobs" / "tra_fild_123.txt"
MOB_DB_FILES = (
	ROOT / "db" / "re" / "mob_db.yml",
	ROOT / "db" / "import" / "mob_db.yml",
)
MOB_AVAIL_FILE = ROOT / "db" / "import" / "mob_avail.yml"

MONSTER_RE = re.compile(
	r"monster\s+.+?\s+(\d+),",
	re.IGNORECASE,
)
COMMENT_RE = re.compile(r"//\s*(\S+)")
AEGIS_RE = re.compile(r"AegisName:\s*(\S+)")
MOB_AVAIL_RE = re.compile(r"^\s*-\s*Mob:\s*(\S+)", re.MULTILINE)

PLAYER_DUMMY_SPRITES = {
	"S_DUMMY_100_HUMANP": ("JOB_NOVICE", {"Sex": "Male"}),
	"S_DUMMY_100_DORAMP": ("JOB_SUMMONER", {"Sex": "Female"}),
}


def sprite_for(aegis: str) -> tuple[str, dict[str, str]]:
	if aegis in PLAYER_DUMMY_SPRITES:
		sprite, extra = PLAYER_DUMMY_SPRITES[aegis]
		return sprite, extra

	upper = aegis.upper()
	if "XLARGE" in upper:
		return "DUMMY_150", {}
	if "LARGE" in upper:
		return "DUMMY_100", {}
	if "MEDIUM" in upper:
		return "DUMMY_50", {}
	if "SMALL" in upper:
		return "DUMMY_10", {}
	return "DUMMY_100", {}


def load_aegis_names() -> dict[int, str]:
	names: dict[int, str] = {}
	current_id: int | None = None
	for path in MOB_DB_FILES:
		if not path.exists():
			continue
		for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
			if line.strip().startswith("- Id:"):
				current_id = int(line.split(":", 1)[1].strip())
				continue
			match = AEGIS_RE.search(line)
			if match and current_id is not None:
				names[current_id] = match.group(1)
				current_id = None
	return names


def collect_spawned_mobs(aegis_by_id: dict[int, str]) -> dict[str, int]:
	spawned: dict[str, int] = {}

	for line in SPAWN_FILE.read_text(encoding="utf-8", errors="replace").splitlines():
		monster = MONSTER_RE.search(line)
		if not monster:
			continue
		mob_id = int(monster.group(1))
		comment = COMMENT_RE.search(line)
		name = comment.group(1) if comment else aegis_by_id.get(mob_id, str(mob_id))
		spawned[name] = mob_id

	return spawned


def render_mob_avail(spawned: dict[str, int], player_only: bool) -> str:
	lines = [
		"# Training ground dummy sprite remaps (tra_fild01/02/03)",
		"# Generated by tools/gen_training_dummy_avail.py --write",
		"# ProAsia clients ship native s_dummy_* sprites; only player-shaped",
		"# dummies need job sprite fallbacks to avoid client gravity errors.",
		"",
		"Header:",
		"  Type: MOB_AVAIL_DB",
		"  Version: 1",
		"",
		"Body:",
	]

	names = sorted(name for name in spawned if name in PLAYER_DUMMY_SPRITES) if player_only else sorted(spawned)
	for name in names:
		sprite, extra = sprite_for(name)
		lines.append(f"  - Mob: {name}")
		lines.append(f"    Sprite: {sprite}")
		for key, value in extra.items():
			lines.append(f"    {key}: {value}")

	return "\n".join(lines) + "\n"


def write_mob_avail(spawned: dict[str, int], player_only: bool) -> None:
	MOB_AVAIL_FILE.parent.mkdir(parents=True, exist_ok=True)
	body = render_mob_avail(spawned, player_only)
	MOB_AVAIL_FILE.write_text(body, encoding="utf-8", newline="\n")
	entry_count = body.count("\n  - Mob:")
	print(f"Wrote {entry_count} entries to {MOB_AVAIL_FILE.relative_to(ROOT)}")


def main() -> None:
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument(
		"--write",
		action="store_true",
		help="Generate db/import/mob_avail.yml for tra_fild training dummies",
	)
	parser.add_argument(
		"--legacy-remaps",
		action="store_true",
		help="Also remap non-player dummies to legacy DUMMY_10/50/100/150 sprites",
	)
	args = parser.parse_args()

	if not SPAWN_FILE.exists():
		raise SystemExit(f"Missing spawn file: {SPAWN_FILE}")

	aegis_by_id = load_aegis_names()
	spawned = collect_spawned_mobs(aegis_by_id)

	if args.write:
		write_mob_avail(spawned, player_only=not args.legacy_remaps)

	avail = set()
	if MOB_AVAIL_FILE.exists():
		avail = set(MOB_AVAIL_RE.findall(MOB_AVAIL_FILE.read_text(encoding="utf-8", errors="replace")))

	print(f"Training dummies in {SPAWN_FILE.name}: {len(spawned)} unique Aegis names")
	for name in sorted(spawned):
		sprite, _ = sprite_for(name)
		mapped = f"->{sprite}" if name in avail else "native"
		print(f"  {name:<28} id={spawned[name]:<6} {mapped}")

	missing_db = [name for name, mob_id in spawned.items() if name not in aegis_by_id.values() and not name.isdigit()]
	if missing_db:
		print("\nWarning: spawn comments / IDs not found in mob_db:")
		for name in sorted(missing_db):
			print(f"  {name}")

	unmapped = sorted(name for name in spawned if name not in avail)
	if unmapped and not args.write:
		print(f"\n{len(unmapped)} mobs have no mob_avail entry. Run with --write to generate remaps.")


if __name__ == "__main__":
	main()
