# Generate db/legendary_hunt_map_drops.yml for Legendary Hunting Missions.
$ErrorActionPreference = "Stop"

$Root = Split-Path $PSScriptRoot -Parent
$MobDb = Join-Path $Root "db\re\mob_db.yml"
$NpcDir = Join-Path $Root "npc"
$Output = Join-Path $Root "db\legendary_hunt_map_drops.yml"

$MinLevel = 220
$MaxLevel = 270
$ScrapMax = 2000
$ScrapMin = 1400
$CoreMaxNormal = 500
$CoreMinNormal = 280
$ScrapMvpMax = 5000
$ScrapMvpMin = 3000
$CoreMvpMax = 1500
$CoreMvpMin = 800

function Get-ScaleRate {
	param([int]$Level, [bool]$IsMvp, [string]$Item)
	$span = [Math]::Max(1, $MaxLevel - $MinLevel)
	$t = [Math]::Min(1.0, [Math]::Max(0.0, ($Level - $MinLevel) / $span))

	if ($IsMvp) {
		if ($Item -eq "scrap") {
			return [int]($ScrapMvpMin + $t * ($ScrapMvpMax - $ScrapMvpMin))
		}
		return [int]($CoreMvpMin + $t * ($CoreMvpMax - $CoreMvpMin))
	}
	if ($Item -eq "scrap") {
		return [int]($ScrapMin + $t * ($ScrapMax - $ScrapMin))
	}
	return [int]($CoreMinNormal + $t * ($CoreMaxNormal - $CoreMinNormal))
}

$mobLevels = @{}
$mobClass = @{}
$mobMvpExp = @{}
$mobName = @{}
$currentId = $null

Get-Content -Path $MobDb -Encoding UTF8 | ForEach-Object {
	if ($_ -match '^\s+- Id: (\d+)') {
		$currentId = [int]$Matches[1]
		return
	}
	if ($null -eq $currentId) { return }
	if ($_ -match '^\s+AegisName: (\S+)') {
		$mobName[$currentId] = $Matches[1]
		return
	}
	if ($_ -match '^\s+Level: (\d+)') {
		$mobLevels[$currentId] = [int]$Matches[1]
		return
	}
	if ($_ -match '^\s+Class: (\S+)') {
		$mobClass[$currentId] = $Matches[1]
		return
	}
	if ($_ -match '^\s+MvpExp: (\d+)') {
		$mobMvpExp[$currentId] = [long]$Matches[1]
	}
}

$mapMobs = @{}

Get-ChildItem -Path $NpcDir -Recurse -Filter "*.txt" | ForEach-Object {
	Get-Content -LiteralPath $_.FullName -Encoding UTF8 -ErrorAction SilentlyContinue | ForEach-Object {
		$line = $_.Trim()
		if (-not $line -or $line.StartsWith("//")) { return }
		$parts = $line -split "`t"
		if ($parts.Count -lt 4) { return }
		if ($parts[1] -notin @("monster", "boss_monster")) { return }
		$map = (($parts[0] -split ",")[0]).Trim()
		if (-not $map) { return }
		$mobField = ($parts[3] -split ",")[0].Trim()
		if ($mobField -notmatch '^\d+$') { return }
		$mid = [int]$mobField
		if (-not $mapMobs.ContainsKey($map)) {
			$mapMobs[$map] = @{}
		}
		if (-not $mapMobs[$map].ContainsKey($mid)) {
			$mapMobs[$map][$mid] = [System.Collections.Generic.HashSet[string]]::new()
		}
		[void]$mapMobs[$map][$mid].Add($parts[1])
	}
}

function Test-IsMvp {
	param([int]$Mid, $SpawnTypes)
	if ($SpawnTypes.Contains("boss_monster")) { return $true }
	if ($mobClass[$Mid] -eq "Boss") { return $true }
	if ($mobMvpExp.ContainsKey($Mid) -and $mobMvpExp[$Mid] -gt 0) { return $true }
	return $false
}

$lines = New-Object System.Collections.Generic.List[string]
[void]$lines.Add("# Legendary Hunting Missions - map-specific drops")
[void]$lines.Add("# Auto-generated by tools/generate_legend_hunt_map_drops.ps1")
[void]$lines.Add("# Rates use n/100000 and ignore server drop bonuses (enable_bonus_map_drops: no).")
[void]$lines.Add("# Normal monsters (Lv220-Lv270): Legend Hunt Scrap 1.40%-2.00%, Core 0.28%-0.50%.")
[void]$lines.Add("# MVP monsters (Lv220+): Scrap 3.00%-5.00%, Core 0.80%-1.50%.")
[void]$lines.Add("# Target: ~24h budget craft / ~48h premium craft at BL250 (~500-600 kills/hour).")
[void]$lines.Add("")
[void]$lines.Add("Header:")
[void]$lines.Add("  Type: MAP_DROP_DB")
[void]$lines.Add("  Version: 2")
[void]$lines.Add("")
[void]$lines.Add("Body:")

$mapCount = 0
$mobCount = 0

foreach ($mapname in ($mapMobs.Keys | Sort-Object)) {
	$specificBlocks = New-Object System.Collections.Generic.List[string]

	foreach ($mid in ($mapMobs[$mapname].Keys | Sort-Object)) {
		if (-not $mobLevels.ContainsKey($mid) -or -not $mobName.ContainsKey($mid)) { continue }
		$level = $mobLevels[$mid]
		if ($level -lt $MinLevel) { continue }

		$mvp = Test-IsMvp -Mid $mid -SpawnTypes $mapMobs[$mapname][$mid]
		$scrapRate = Get-ScaleRate -Level $level -IsMvp $mvp -Item "scrap"
		$coreRate = Get-ScaleRate -Level $level -IsMvp $mvp -Item "core"
		$name = $mobName[$mid]

		[void]$specificBlocks.Add("      - Monster: $name")
		[void]$specificBlocks.Add("        Drops:")
		[void]$specificBlocks.Add("          - Index: 0")
		[void]$specificBlocks.Add("            Item: Legend_Hunt_Scrap")
		[void]$specificBlocks.Add("            Rate: $scrapRate")
		[void]$specificBlocks.Add("          - Index: 1")
		[void]$specificBlocks.Add("            Item: Legend_Hunt_Core")
		[void]$specificBlocks.Add("            Rate: $coreRate")
		$mobCount++
	}

	if ($specificBlocks.Count -eq 0) { continue }

	$mapCount++
	[void]$lines.Add("  - Map: $mapname")
	[void]$lines.Add("    SpecificDrops:")
	foreach ($block in $specificBlocks) {
		[void]$lines.Add($block)
	}
	[void]$lines.Add("")
}

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($Output, ($lines -join "`n").TrimEnd() + "`n", $utf8NoBom)

Write-Host "Wrote $Output"
Write-Host "Maps: $mapCount, monster entries: $mobCount"
