#!/usr/bin/env python3
"""Generate map_drops entries for Legendary Hunting Missions materials."""

import re
import os
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MOB_DB = os.path.join(ROOT, "db", "re", "mob_db.yml")
NPC_DIR = os.path.join(ROOT, "npc")
OUTPUT = os.path.join(ROOT, "db", "legendary_hunt_map_drops.yml")

MIN_LEVEL = 220
MAX_LEVEL = 270

# Normal monsters (n/100000). Caps: scrap 2.00%, core 0.50%.
# Tuned for ~24h budget crafts (280/55) and ~48h premium (480/90) at BL250,
# assuming ~500-600 kills/hour on Lv250 fields with fixed map drops.
SCRAP_MAX = 2000        # 2.00% at Lv270
SCRAP_MIN = 1400        # 1.40% at Lv220  (~1.76% at Lv250)
CORE_MAX_NORMAL = 500   # 0.50% at Lv270
CORE_MIN_NORMAL = 280   # 0.28% at Lv220  (~0.41% at Lv250)

# MVP bonus (still fixed map drops; not affected by server drop bonuses).
SCRAP_MVP_MAX = 5000    # 5.00% at Lv270
SCRAP_MVP_MIN = 3000    # 3.00% at Lv220
CORE_MVP_MAX = 1500     # 1.50% at Lv270
CORE_MVP_MIN = 800      # 0.80% at Lv220


def load_mobs():
	mob_levels = {}
	mob_class = {}
	mob_mvp_exp = {}
	mob_name = {}
	current_id = None

	with open(MOB_DB, encoding="utf-8") as f:
		for line in f:
			m = re.match(r"  - Id: (\d+)", line)
			if m:
				current_id = int(m.group(1))
				continue
			if current_id is None:
				continue
			m = re.match(r"    AegisName: (\S+)", line)
			if m:
				mob_name[current_id] = m.group(1)
				continue
			m = re.match(r"    Level: (\d+)", line)
			if m:
				mob_levels[current_id] = int(m.group(1))
				continue
			m = re.match(r"    Class: (\S+)", line)
			if m:
				mob_class[current_id] = m.group(1)
				continue
			m = re.match(r"    MvpExp: (\d+)", line)
			if m:
				mob_mvp_exp[current_id] = int(m.group(1))

	return mob_levels, mob_class, mob_mvp_exp, mob_name


def load_spawns():
	map_mobs = defaultdict(lambda: defaultdict(set))

	for root, _, files in os.walk(NPC_DIR):
		for fn in files:
			if not fn.endswith(".txt"):
				continue
			path = os.path.join(root, fn)
			with open(path, encoding="utf-8", errors="ignore") as f:
				for line in f:
					line = line.strip()
					if not line or line.startswith("//"):
						continue
					parts = line.split("\t")
					if len(parts) < 4:
						continue
					if parts[1] not in ("monster", "boss_monster"):
						continue
					mapname = parts[0].split(",")[0].strip()
					if not mapname:
						continue
					mob_field = parts[3].split(",")[0].strip()
					try:
						mid = int(mob_field)
					except ValueError:
						continue
					map_mobs[mapname][mid].add(parts[1])

	return map_mobs


def is_mvp(mid, mob_class, mob_mvp_exp, spawn_types):
	if "boss_monster" in spawn_types:
		return True
	if mob_class.get(mid) == "Boss":
		return True
	return mob_mvp_exp.get(mid, 0) > 0


def scale_rate(level, is_mvp, item):
	span = max(1, MAX_LEVEL - MIN_LEVEL)
	t = min(1.0, max(0.0, (level - MIN_LEVEL) / span))

	if is_mvp:
		if item == "scrap":
			return int(SCRAP_MVP_MIN + t * (SCRAP_MVP_MAX - SCRAP_MVP_MIN))
		return int(CORE_MVP_MIN + t * (CORE_MVP_MAX - CORE_MVP_MIN))

	if item == "scrap":
		return int(SCRAP_MIN + t * (SCRAP_MAX - SCRAP_MIN))
	return int(CORE_MIN_NORMAL + t * (CORE_MAX_NORMAL - CORE_MIN_NORMAL))


def main():
	mob_levels, mob_class, mob_mvp_exp, mob_name = load_mobs()
	map_mobs = load_spawns()

	lines = [
		"# Legendary Hunting Missions - map-specific drops",
		"# Auto-generated by tools/generate_legend_hunt_map_drops.py",
		"# Rates use n/100000 and ignore server drop bonuses (enable_bonus_map_drops: no).",
		"# Normal monsters (Lv220-Lv270): Legend Hunt Scrap 1.40%-2.00%, Core 0.28%-0.50%.",
		"# MVP monsters (Lv220+): Scrap 3.00%-5.00%, Core 0.80%-1.50%.",
		"# Target: ~24h budget craft / ~48h premium craft at BL250 (~500-600 kills/hour).",
		"",
		"Header:",
		"  Type: MAP_DROP_DB",
		"  Version: 2",
		"",
		"Body:",
	]

	map_count = 0
	mob_count = 0

	for mapname in sorted(map_mobs):
		specific_blocks = []

		for mid in sorted(map_mobs[mapname]):
			level = mob_levels.get(mid)
			name = mob_name.get(mid)
			if level is None or name is None or level < MIN_LEVEL:
				continue

			mvp = is_mvp(mid, mob_class, mob_mvp_exp, map_mobs[mapname][mid])
			scrap_rate = scale_rate(level, mvp, "scrap")
			core_rate = scale_rate(level, mvp, "core")

			specific_blocks.append(
				f"      - Monster: {name}\n"
				f"        Drops:\n"
				f"          - Index: 0\n"
				f"            Item: Legend_Hunt_Scrap\n"
				f"            Rate: {scrap_rate}\n"
				f"          - Index: 1\n"
				f"            Item: Legend_Hunt_Core\n"
				f"            Rate: {core_rate}"
			)
			mob_count += 1

		if not specific_blocks:
			continue

		map_count += 1
		lines.append(f"  - Map: {mapname}")
		lines.append("    SpecificDrops:")
		lines.extend(specific_blocks)
		lines.append("")

	with open(OUTPUT, "w", encoding="utf-8", newline="\n") as f:
		f.write("\n".join(lines).rstrip() + "\n")

	print(f"Wrote {OUTPUT}")
	print(f"Maps: {map_count}, monster entries: {mob_count}")


if __name__ == "__main__":
	main()
