#!/usr/bin/env python3
"""Generate map_drops entries for Legendary Hunting Missions materials."""

import re
import os
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MOB_DB = os.path.join(ROOT, "db", "re", "mob_db.yml")
NPC_DIR = os.path.join(ROOT, "npc")
OUTPUT = os.path.join(ROOT, "db", "import", "map_drops.yml")

MIN_LEVEL = 220
MAX_LEVEL = 270
SCRAP_MAX = 3000       # 3.00% normal cap
CORE_MAX_NORMAL = 3000 # 3.00% normal cap (scales slower via floor)
SCRAP_MVP_MAX = 15000  # 15.00% MVP medium cap
CORE_MVP_MAX = 25000   # 25.00% MVP cap
SCRAP_MIN = 400        # 0.40% at level 220
CORE_MIN_NORMAL = 150  # 0.15% at level 220
RATE_MULTIPLIER = 0.8  # Global rate adjustment (0.8 = 20% decrease)


def load_mobs():
	mob_levels = {}
	mob_class = {}
	mob_mvp_exp = {}
	mob_name = {}
	current_id = None

	with open(MOB_DB, encoding="utf-8") as f:
		for line in f:
			m = re.match(r"  - Id: (\d+)", line)
			if m:
				current_id = int(m.group(1))
				continue
			if current_id is None:
				continue
			m = re.match(r"    AegisName: (\S+)", line)
			if m:
				mob_name[current_id] = m.group(1)
				continue
			m = re.match(r"    Level: (\d+)", line)
			if m:
				mob_levels[current_id] = int(m.group(1))
				continue
			m = re.match(r"    Class: (\S+)", line)
			if m:
				mob_class[current_id] = m.group(1)
				continue
			m = re.match(r"    MvpExp: (\d+)", line)
			if m:
				mob_mvp_exp[current_id] = int(m.group(1))

	return mob_levels, mob_class, mob_mvp_exp, mob_name


def load_spawns():
	map_mobs = defaultdict(lambda: defaultdict(set))

	for root, _, files in os.walk(NPC_DIR):
		for fn in files:
			if not fn.endswith(".txt"):
				continue
			path = os.path.join(root, fn)
			with open(path, encoding="utf-8", errors="ignore") as f:
				for line in f:
					line = line.strip()
					if not line or line.startswith("//"):
						continue
					parts = line.split("\t")
					if len(parts) < 4:
						continue
					if parts[1] not in ("monster", "boss_monster"):
						continue
					mob_field = parts[3].split(",")[0].strip()
					try:
						mid = int(mob_field)
					except ValueError:
						continue
					map_mobs[parts[0]][mid].add(parts[1])

	return map_mobs


def is_mvp(mid, mob_class, mob_mvp_exp, spawn_types):
	if "boss_monster" in spawn_types:
		return True
	if mob_class.get(mid) == "Boss":
		return True
	return mob_mvp_exp.get(mid, 0) > 0


def scale_rate(level, is_mvp, item):
	span = max(1, MAX_LEVEL - MIN_LEVEL)
	t = min(1.0, max(0.0, (level - MIN_LEVEL) / span))

	if is_mvp:
		if item == "scrap":
			return max(1, int((5000 + t * (SCRAP_MVP_MAX - 5000)) * RATE_MULTIPLIER))
		return max(1, int((10000 + t * (CORE_MVP_MAX - 10000)) * RATE_MULTIPLIER))

	if item == "scrap":
		return max(1, int((SCRAP_MIN + t * (SCRAP_MAX - SCRAP_MIN)) * RATE_MULTIPLIER))
	return max(1, int((CORE_MIN_NORMAL + t * (CORE_MAX_NORMAL - CORE_MIN_NORMAL)) * RATE_MULTIPLIER))


def main():
	mob_levels, mob_class, mob_mvp_exp, mob_name = load_mobs()
	map_mobs = load_spawns()

	lines = [
		"# Legendary Hunting Missions - map-specific drops",
		"# Auto-generated by tools/generate_legend_hunt_map_drops.py",
		"# Rates use n/100000 and ignore server drop bonuses when enable_bonus_map_drops is off.",
		"# Normal monsters (220+): up to 2.4% per material (scales with level).",
		"# MVP monsters (220+): scrap up to 12%, core up to 20% (scales with level).",
		"",
		"Header:",
		"  Type: MAP_DROP_DB",
		"  Version: 2",
		"",
		"Body:",
	]

	map_count = 0
	mob_count = 0

	for mapname in sorted(map_mobs):
		specific_blocks = []

		for mid in sorted(map_mobs[mapname]):
			level = mob_levels.get(mid)
			name = mob_name.get(mid)
			if level is None or name is None or level < MIN_LEVEL:
				continue

			mvp = is_mvp(mid, mob_class, mob_mvp_exp, map_mobs[mapname][mid])
			scrap_rate = scale_rate(level, mvp, "scrap")
			core_rate = scale_rate(level, mvp, "core")

			specific_blocks.append(
				f"      - Monster: {name}\n"
				f"        Drops:\n"
				f"          - Index: 0\n"
				f"            Item: Legend_Hunt_Scrap\n"
				f"            Rate: {scrap_rate}\n"
				f"          - Index: 1\n"
				f"            Item: Legend_Hunt_Core\n"
				f"            Rate: {core_rate}"
			)
			mob_count += 1

		if not specific_blocks:
			continue

		map_count += 1
		lines.append(f"  - Map: {mapname}")
		lines.append("    SpecificDrops:")
		lines.extend(specific_blocks)
		lines.append("")

	with open(OUTPUT, "w", encoding="utf-8", newline="\n") as f:
		f.write("\n".join(lines).rstrip() + "\n")

	print(f"Wrote {OUTPUT}")
	print(f"Maps: {map_count}, monster entries: {mob_count}")


if __name__ == "__main__":
	main()
